//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetActiviteVisiteurWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class activite_visiteursEntities : DbContext
    {
        public activite_visiteursEntities()
            : base("name=activite_visiteursEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activite_compl> activite_compl { get; set; }
        public virtual DbSet<inviter> inviter { get; set; }
        public virtual DbSet<praticien> praticien { get; set; }
        public virtual DbSet<rapport_visite> rapport_visite { get; set; }
        public virtual DbSet<realiser> realiser { get; set; }
        public virtual DbSet<visiteur> visiteur { get; set; }
    }
}
