//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetActiviteVisiteurWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class praticien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public praticien()
        {
            this.inviter = new HashSet<inviter>();
            this.rapport_visite = new HashSet<rapport_visite>();
        }
    
        public short PRA_NUM { get; set; }
        public string PRA_NOM { get; set; }
        public string PRA_PRENOM { get; set; }
        public string PRA_ADRESSE { get; set; }
        public string PRA_CP { get; set; }
        public string PRA_VILLE { get; set; }
        public double PRA_COEFNOTORIETE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inviter> inviter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rapport_visite> rapport_visite { get; set; }
    }
}
