//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetActiviteVisiteurWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rapport_visite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rapport_visite()
        {
            this.offrir = new HashSet<offrir>();
        }
    
        public int RAP_NUM { get; set; }
        public System.DateTime RAP_DATE { get; set; }
        public string RAP_MOTIF { get; set; }
        public string RAP_BILAN { get; set; }
        public short PRA_NUM { get; set; }
        public string VIS_MATRICULE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<offrir> offrir { get; set; }
        public virtual praticien praticien { get; set; }
        public virtual visiteur visiteur { get; set; }
    }
}
